### PR TITLE
Support MYSQL_TYPE_NEWDECIMAL

### LINKED ISSUE #18: Unable to Decode sum(int(11)) Values in MySQL
I am not able to decode an integer for a query like
```sql
SELECT sum(unread_messages_count) `count` FROM `chat_participant` WHERE `user_id` = \(bind: userId)
```
where `unread_messages_count` is an `int(11)` in mysql. Going through the debugger, it seems that we hit the [`default` case on line 313 of `MySQLData.swift`](https://github.com/vapor/mysql-nio/blob/master/Sources/MySQLNIO/MySQLData.swift#L313).

The value of `MySQLData.type` that the switch statement is switching off of has a raw value of `246`. Type `246` is [`newdecimal` from MySQLProtocol+DataType.swift line 68](https://github.com/vapor/mysql-nio/blob/master/Sources/MySQLNIO/Protocol/MySQLProtocol%2BDataType.swift#L68). Should we handle converting `newdecimal` to `Int`? The default `.sum()` aggregation function tries to decode to `Int` as well and I was having trouble with the following code:
```swift
    return ChatParticipant.query(on: db)
      .filter(\.$user.$id, .equal, userId)
      .sum(\.$numberOfUnreadMessages)
      .unwrap(or: Abort(.internalServerError, reason: "Unable to unwrap sum(numberOfUnreadMessages) for user \(userId)"))
```

I was getting the same decoding error as the raw query.

I can see why they might use decimal as the summed up columns might not be integers. Looking at the MySQLNIO decoding logic, it doesn't seem like we handle decoding of `newdecimal` anywhere. `newdecimal` seems to be unimplemented.

~~Also, does decoding sum as int by default make sense? (I can be convinced either way)~~ This is dynamic based on the type of the field. The "issue" is that for an int column, mysql is returning a `newdecimal` that cannot be parsed as an int.

I am using the latest docker image for MySQL 5.7.

My work around for this bug was to [cast the sum](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast) aggregate as `SIGNED `
```sql
SELECT CAST(sum(unread_messages_count) as SIGNED) `count` FROM `chat_participant` WHERE `user_id` = \(bind: userId)
```

Added test case that fails:
```swift
    func testDecodingSumOfInts() throws {
        let conn = try MySQLConnection.test(on: self.eventLoop).wait()
        defer { try! conn.close().wait() }
        let dropResults = try conn.simpleQuery("DROP TABLE IF EXISTS foos").wait()
        XCTAssertEqual(dropResults.count, 0)
        let createResults = try conn.simpleQuery("CREATE TABLE foos (`item_count` int(11))").wait()
        XCTAssertEqual(createResults.count, 0)
        let rows = try conn.simpleQuery("SELECT sum(`item_count`) as sum from foos").wait()
        guard rows.count == 1 else {
            XCTFail("invalid row count")
            return
        }
        XCTAssertNotNil(rows[0].column("sum"))
        XCTAssertEqual(rows[0].column("sum")?.string, "0")
        XCTAssertEqual(rows[0].column("sum")?.double, 0)
        XCTAssertEqual(rows[0].column("sum")?.int, 0)
    }
```
Debugger returns
```
(lldb) po rows[0].column("sum")
▿ Optional<MySQLData>
  ▿ some : nil
    ▿ type : MYSQL_TYPE_NEWDECIMAL
      - rawValue : 246
    - format : MySQLNIO.MySQLData.Format.text
    - buffer : nil
    - isUnsigned : false
```

### PR DESCRIPTION
**Pull request by thecheatah**
Adds support for `MYSQL_TYPE_NEWDECIMAL` conversion on `MySQLData` (#19, fixes #18).

### CODE REVIEW

**Comment by tanner0101** [comment]
> newdecimal appears to be a length encoded string as documented here: https://mariadb.com/kb/en/resultset-row/#decimal-binary-encoding
> From observation a 0 is represented as a nil buffer. 1 is represented as the string 1. From the documentation above, numbers can also be 123.456.

From: https://github.com/vapor/mysql-nio/issues/18

> DECIMAL has no fixed size, so will be encoded as string<lenenc>. An DECIMAL(10,2) with a value of -15.5 is stored as

From: https://mariadb.com/kb/en/resultset-row/#decimal-binary-encoding

I don't see any mention here that `NULL` should be interpreted as `0`. Additionally, MySQL's result set specifies whether each field is null or not using a separate bitmap. In other words, calculating null and length-encoded strings are separate from each other. 

I ran the queries from this test in TablePlus and the client there gives back `NULL` for the `SUM` column which is what I would expect. There are no columns to aggregate so it's not possible to derive a sum. 

Screen Shot 2020-03-19 at 10 56 57 AM

**Comment by thecheatah** [comment]
@tanner0101 It's not representing a nil by having a nil buffer. If a new decimal has a nil buffer then the represented value for it is 0. I verified this with MySqlworkbench that summing 0 rows results in a 0 and in mysql-nio it's coming back as a new decimal with a nil buffer. My other example that had a similar issue, it was a new decimal but the buffer had the length encoded string "1".

Does that make sense?

**Comment by thecheatah** [comment]
@tanner0101 I just reread your message and tried to example and you are right, I do get a null for sum in mysqlworkbench. But in my example of the table from my app, I get a 0.

**Comment by thecheatah** [comment]
@tanner0101  I deleted my previous two comments. I had mixed count with sum that's why I was getting different results. You might be right where if a new decimal has a nil buffer it might just be a nil. I have to try to get an example of a 0 represented as a new decimal

**Comment by thecheatah** [comment]
@tanner0101, I have rolled back the changes that mapped the empty buffer to a nil. I have kept the remaining decoding changes for `newdecimal`. I have also added tests for sum with and without rows.

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-rc.1.1](https://github.com/vapor/mysql-nio/releases/tag/1.0.0-rc.1.1)

**Pull request merged**
